export const AGREGAR_PACIENTE = 'agregarPacienteContagiado'
export const ELIMINAR_PTE = 'eliminarPte'
export const MODIFICAR_PTE = 'modificarPte'
export const AGREGAR_RECUPERADO = 'agregarPacienteRecuperado'
export const AGREGAR_FALLECIDO = 'agregarPacienteFallecido'
